# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScriptFailarmy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 482)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_ModifyFileName = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ModifyFileName.setGeometry(QtCore.QRect(20, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ModifyFileName.setFont(font)
        self.btn_ModifyFileName.setObjectName("btn_ModifyFileName")
        self.btn_DataToShmoo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_DataToShmoo.setGeometry(QtCore.QRect(20, 70, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_DataToShmoo.setFont(font)
        self.btn_DataToShmoo.setObjectName("btn_DataToShmoo")
        self.btn_GeneratePattern = QtWidgets.QPushButton(self.centralwidget)
        self.btn_GeneratePattern.setGeometry(QtCore.QRect(20, 130, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_GeneratePattern.setFont(font)
        self.btn_GeneratePattern.setObjectName("btn_GeneratePattern")
        self.label_runStatus = QtWidgets.QLabel(self.centralwidget)
        self.label_runStatus.setGeometry(QtCore.QRect(50, 390, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_runStatus.setFont(font)
        self.label_runStatus.setText("")
        self.label_runStatus.setObjectName("label_runStatus")
        self.textEdit_OutputInfo = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_OutputInfo.setGeometry(QtCore.QRect(280, 10, 311, 421))
        self.textEdit_OutputInfo.setObjectName("textEdit_OutputInfo")
        self.btn_SortFileToNES = QtWidgets.QPushButton(self.centralwidget)
        self.btn_SortFileToNES.setGeometry(QtCore.QRect(20, 190, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_SortFileToNES.setFont(font)
        self.btn_SortFileToNES.setObjectName("btn_SortFileToNES")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_ModifyFileName.setText(_translate("MainWindow", "ModifyFileName"))
        self.btn_DataToShmoo.setText(_translate("MainWindow", "DataToShmoo"))
        self.btn_GeneratePattern.setText(_translate("MainWindow", "GenaratePattern"))
        self.btn_SortFileToNES.setText(_translate("MainWindow", "SortFileToNES"))
